package csis1410.SimFlame;

/**
 * Contains methods for saving/loading the state of the world to/from disk
 */
public class Serializer {
   
   // Methods
   
   /**
    * Saves the current state of the world to a file.
    * 
    * @param world the world to save
    * @param filename the path of the file to save it to
    */
   public static void save(World world, String filename) {
      // TODO: Write me
   }
   
   /**
    * Loads a previously saved World from a file.
    * 
    * @param filename the path of the file to attempt loading
    * @return the world that was loaded
    * @return null if filename is not a valid path to an existing file
    * @return null if filename is valid but deserialization fails
    */
   public static World load(String filename) {
      // TODO: Write me
   }
   
   /**
    * Takes a world and returns a serialized version in a String
    * 
    * @param world the world to serialize
    * @return the serialized version as a String
    */
   public static String serialize(World world) {
      // TODO: Write me
   }
   
   /**
    * Takes a String following the same specification as those
    * generated by the {@link #serialize(World) serialize} method.
    * If the given string follows the proper specification, it deserializes
    * it into an instance of World.
    * 
    * @param string the String to deserialize
    * @return the world
    * @return null if deserialization fails
    */
   public static World deserialize(String string) {
      // TODO: Write me
   }
   
}